### ISSUE TITLE
GoMainCheckWindow에서 동시에 여러개의 창 닫기

### ISSUE THREAD

**Issue by suinj8** [JBNU-WINDOWS-PROGRAMMING-2022-PROJECT/Tomorrow_Is_Stock_King_#7]
GameMainWindow, SettingWindow, GoMainCheckWindow가 켜져있는 상태에서
에 버튼을 누르면 세개의 창이 모두 닫히고 MainWindow창이 열려야 함
현재는 MainWindow만 열리는 상태 (나머지 그대로 존재)

**Comment by tlstmdck** [comment]
메인 창을 킨후 
            foreach (Window window in System.Windows.Application.Current.Windows)
            {
                if(window.Title != "MainWindow")
                {
                    window.Close();
                }
            }
이용

**Comment by suinj8** [comment]
> 메인 창을 킨후 foreach (Window window in System.Windows.Application.Current.Windows) { if(window.Title != "MainWindow") { window.Close(); } } 이용

기가 막혔습니다! 구웃
